# Generated by Django 4.1.6 on 2023-02-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('entry', models.TextField(null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
