# Generated by Django 4.1.5 on 2023-01-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_imageupload_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='file',
            field=models.FileField(default='Instagram.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('dispatch-store', 'Dispatch store'), ('door-delivery', 'Door delivery')], default='door-delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='means_of_payment',
            field=models.CharField(choices=[('mpesa', 'M-pesa'), ('bank', 'Bank'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
    ]
