# Generated by Django 4.1.5 on 2023-01-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_order_means_of_payment_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='consent',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('door-delivery', 'Door delivery'), ('dispatch-store', 'Dispatch store')], default='door-delivery', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='means_of_payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-pesa'), ('bank', 'Bank')], default='cash', max_length=50, null=True),
        ),
    ]
