# Generated by Django 4.1.6 on 2023-02-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_cart_consent_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('door-delivery', 'Door delivery'), ('dispatch-store', 'Dispatch store')], default='door-delivery', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
