# Generated by Django 4.1.6 on 2023-02-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_cart_consent_alter_order_means_of_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='consent',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('dispatch-store', 'Dispatch store'), ('door-delivery', 'Door delivery')], default='door-delivery', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='means_of_payment',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('mpesa', 'M-pesa')], default='cash', max_length=50, null=True),
        ),
    ]
