# Generated by Django 4.1.6 on 2023-02-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_order_means_of_payment_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='means_of_payment',
            field=models.CharField(choices=[('mpesa', 'M-pesa'), ('bank', 'Bank'), ('cash', 'Cash')], default='cash', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cart', 'Cart'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock')], default='available', max_length=50),
        ),
    ]
